name: Build the Ansible docsite

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - master

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  build-docsite:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Pip install nox
        run: python -Im pip install nox
      - name: Generate assets for the docs landing page
        env:
          PYTHONWARNINGS: >-  # pip vendors deprecated `setuptools`' `pkg_resources`
            error,once:pkg_resources is deprecated as an API.:DeprecationWarning:pip._internal.metadata.importlib._envs
        run: python -Im nox -s build
      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
          enable_jekyll: false
          user_name: QubitPi
          user_email: jack20220723@gmail.com
          cname: ansible.qubitpi.org
